### PR TITLE
FIND install: extract ALL required files

### LINKED ISSUE #236: Find server installation, data and templates folders missing
I tried the Find server install option yesterday.
The script ran through successfully, but the findserver did not start. The service was in failed state.
Further investigation pointed to missing data and templates folders. I checked in the install zip and these should indeed be in the current directory when executing the find server. Copying these from the zip file to the /var/lib/findserver directory solved this issue. However, I am not sure these should be there. Maybe there is an environment variable to put it in a more appropriate place.
I believe the install script should be extended to put these directories and file in the appropriate place.

### PR DESCRIPTION
**Pull request by mstormi**
Fixes #236 

Signed-off-by: Markus Storm <markus.storm@gmx.net> (github: mstormi)

### CODE REVIEW

**Comment by mstormi** [comment]
not sure why this LF breaker patch is about to be committed again ? It's supposed to be in since 2 days.

File: openhabian-setup.sh [hunk 1]
```diff
@@ -1060,39 +1060,38 @@ HABian GitHub issue."
...
+    FINDADMINPASS=$(whiptail --title "findserver MQTT Setup" --passwordbox "Enter a password for the FIND admin user on your MQTT broker:" 15 80 $DEFAULTFINDPASS 3>&1 1>&2 2>&3)
     cond_redirect /usr/bin/mosquitto_passwd -b ${MOSQUITTO_PASSWD} ${FINDADMIN} ${FINDADMINPASS} || FAILED=1
     if [ $? -ne 0 ]; then echo "FAILED"; exit 1; fi
   fi
   /bin/sed -e "s|%MQTTSERVER|${MQTTSERVER}|g" -e "s|%MQTTPORT|${MQTTPORT}|g" -e "s|%FINDADMIN|${FINDADMIN}|g" -e "s|%FINDADMINPASS|${FINDADMIN_PASS}|g" -e "s|%FINDPORT|${FINDPORT}|g" -e "s|%FINDSERVER|${FINDSERVER}|g" ${SCRIPTDIR}/includes/findserver.service >${FIND_SYSTEMCTL}
   /bin/sed -e "s|%MQTTSERVER|${MQTTSERVER}|g" -e "s|%MQTTPORT|${MQTTPORT}|g" -e "s|%FINDPORT|${FINDPORT}|g" -e "s|%FINDSERVER|${FINDSERVER}|g" ${SCRIPTDIR}/includes/findserver >${FIND_DEFAULT}
 
 
-  /bin/rm -f ${FIND_TMP} ${CLIENT_TMP}
+  /bin/rm -f ${FIND_TMP} ${CLIENT_TMP} ${FIND_DSTDIR}/findserver
```
Comment (ThomDietrich) [inline openhabian-setup.sh]: Also "fingerprint" ?

**Comment by ThomDietrich** [comment]
Maybe because your repo master is still on the old revision

File: openhabian-setup.sh (hunk 1 above)
Comment (mstormi) [reply openhabian-setup.sh]: no

Comment (ThomDietrich) [reply openhabian-setup.sh]: But then it's available twice.
May I suggest something instead of the above. That is how I'd do something like this:

```shell
unzip ${FIND_TMP} -d ${FIND_DSTDIR}
ln -s ${FIND_DSTDIR}/findserver /usr/sbin/findserver
ln -s ${FIND_DSTDIR}/fingerprint /usr/sbin/fingerprint
```

Comment (mstormi) [reply openhabian-setup.sh]: no, fingerprint isn't contained in the archive.
Then again, $FIND_TMP  in the unzip line is bad, it must read $CLIENT_TMP
Ok, will change that and do a ln for the findserver binary

Comment (ThomDietrich) [reply openhabian-setup.sh]: Ah sorry, didn't see that detail. Now remove the `/bin/rm -f ${FIND_DSTDIR}/findserver` and we are good to go ;)

Comment (mstormi) [reply openhabian-setup.sh]: here you are

**Comment by ThomDietrich** [comment]
Looks good! Thanks!
